import type {AppState,Configuration,ContextLocator,HistoryDestination,Id,ReferenceSystem,ReturnContext} from '../domain/types';
export interface DomainIndex {systems:Record<Id,ReferenceSystem>}
const same=(a:ContextLocator,b:ContextLocator)=>JSON.stringify(a)===JSON.stringify(b);
const cfg=(i:DomainIndex,s:Id,c:Id)=>i.systems[s]?.configurations[c];
const root=(s:Id,c:Configuration):ContextLocator=>({kind:'entity',systemId:s,configurationId:c.id,entityId:c.rootEntityId});
const exists=(c:Configuration,l:ContextLocator)=>l.kind==='entity'?!!c.entities[l.entityId]:l.kind==='connection'?!!c.connections[l.connectionId]:l.kind==='representative_member'?!!c.entities[l.aggregateId]&&l.path.every(id=>!!c.entities[id]):true;
const path=(c:Configuration,l:ContextLocator)=>{if(l.kind!=='entity')return [];const out:Id[]=[];let cur:import('../domain/types').Entity|undefined=c.entities[l.entityId];while(cur){out.unshift(cur.id);cur=cur.parentId?c.entities[cur.parentId]:undefined;}return out};
const push=(s:AppState,d:HistoryDestination):AppState=>{const history=s.appHistory.slice(0,s.historyIndex+1);history.push(d);return {...s,appHistory:history,historyIndex:history.length-1}}
export function activeConfiguration(i:DomainIndex,s:AppState){const c=cfg(i,s.explore.systemId,s.explore.configurationId);if(!c)throw new Error('Active configuration unavailable');return c}
export function createInitialState(i:DomainIndex,systemId='nvidia-dgx-h100-superpod'):AppState{const sys=i.systems[systemId];if(!sys)throw new Error(`Unknown initial system ${systemId}`);const c=Object.values(sys.configurations)[0];if(!c)throw new Error('Initial system has no configuration');const r=root(systemId,c);return {view:'explore',explore:{systemId,configurationId:c.id,scenarioId:c.defaultScenarioId,structuralLocation:r,structuralHistory:[r],detailVisible:true},concepts:{query:''},appHistory:[{view:'explore',locator:r}],historyIndex:0}}
export const inspect=(s:AppState,target?:ContextLocator):AppState=>({...s,explore:{...s.explore,preview:target}});
export const select=(s:AppState,target:ContextLocator):AppState=>({...s,explore:{...s.explore,selection:target,preview:undefined}});
export const clearSelection=(s:AppState):AppState=>({...s,explore:{...s.explore,selection:undefined}});
export const toggleDetail=(s:AppState):AppState=>({...s,explore:{...s.explore,detailVisible:!s.explore.detailVisible}});
export function enter(i:DomainIndex,s:AppState,target:ContextLocator):AppState{if(target.kind!=='entity'&&target.kind!=='representative_member')throw new Error('Enter requires a structural target');const c=cfg(i,target.systemId,target.configurationId);if(!c||!exists(c,target))throw new Error('Enter destination unavailable');const n={...s,view:'explore' as const,explore:{...s.explore,systemId:target.systemId,configurationId:target.configurationId,structuralLocation:target,selection:undefined,preview:undefined,structuralHistory:[...s.explore.structuralHistory,target],traversalOrigin:undefined}};return push(n,{view:'explore',locator:target})}
export function follow(i:DomainIndex,s:AppState,destination:ContextLocator,origin:ContextLocator){const n=enter(i,s,destination);return {...n,explore:{...n.explore,traversalOrigin:origin}}}
export function changeScenario(i:DomainIndex,s:AppState,id:Id){const c=activeConfiguration(i,s);if(!c.scenarios[id])throw new Error(`Unknown scenario ${id}`);return {...s,explore:{...s.explore,scenarioId:id}}}
export function switchConfiguration(i:DomainIndex,s:AppState,systemId:Id,configurationId:Id){const c=cfg(i,systemId,configurationId);if(!c)throw new Error('Destination configuration unavailable');const r=root(systemId,c);return push({...s,view:'explore',explore:{...s.explore,systemId,configurationId,scenarioId:c.defaultScenarioId,structuralLocation:r,selection:undefined,preview:undefined,structuralHistory:[r],traversalOrigin:undefined},returnContext:undefined},{view:'explore',locator:r})}
export function openConcept(i:DomainIndex,s:AppState,conceptId:Id,origin?:ContextLocator){let rc=s.returnContext;if(origin&&s.view==='explore'){const c=activeConfiguration(i,s);const label=origin.kind==='entity'?(c.entities[origin.entityId]?.name??origin.entityId):origin.kind==='connection'?(c.connections[origin.connectionId]?.name??origin.connectionId):'Explore';rc={kind:'explore_origin',systemId:s.explore.systemId,configurationId:s.explore.configurationId,scenarioId:s.explore.scenarioId,structuralLocation:s.explore.structuralLocation,structuralPath:path(c,s.explore.structuralLocation),selection:s.explore.selection,sourceConceptId:conceptId,label:`Return to ${label}`} satisfies ReturnContext}const l:ContextLocator={kind:'concept',conceptId};return push({...s,view:'concepts',concepts:{...s.concepts,conceptId},explore:{...s.explore,preview:undefined},returnContext:rc},{view:'concepts',locator:l})}
export function openConceptDirect(s:AppState,conceptId:Id){const l:ContextLocator={kind:'concept',conceptId};return push({...s,view:'concepts',concepts:{...s.concepts,conceptId},explore:{...s.explore,preview:undefined},returnContext:undefined},{view:'concepts',locator:l})}
export function openExploreDirect(s:AppState){const l=s.explore.structuralLocation;return push({...s,view:'explore',explore:{...s.explore,preview:undefined},returnContext:undefined},{view:'explore',locator:l})}

export function conceptToExploreOccurrence(i:DomainIndex,s:AppState,occ:{systemId:Id;configurationId:Id;target:{type:'entity'|'connection'|'configuration';id:Id}}){if(s.view!=='concepts'||!s.concepts.conceptId)throw new Error('Active concept required');const c=cfg(i,occ.systemId,occ.configurationId);if(!c)throw new Error('Occurrence configuration unavailable');let d=root(occ.systemId,c),selection:ContextLocator|undefined;if(occ.target.type==='entity'){const e=c.entities[occ.target.id];if(!e)throw new Error('Occurrence entity unavailable');if(e.parentId){d={kind:'entity',systemId:occ.systemId,configurationId:occ.configurationId,entityId:e.parentId};selection={kind:'entity',systemId:occ.systemId,configurationId:occ.configurationId,entityId:e.id}}else d={kind:'entity',systemId:occ.systemId,configurationId:occ.configurationId,entityId:e.id}}else if(occ.target.type==='connection'){const con=c.connections[occ.target.id];if(!con)throw new Error('Occurrence connection unavailable');const e=c.entities[con.endpointIds[0]];if(e)d={kind:'entity',systemId:occ.systemId,configurationId:occ.configurationId,entityId:e.parentId??e.id};selection={kind:'connection',systemId:occ.systemId,configurationId:occ.configurationId,connectionId:con.id}}const cross=s.explore.systemId!==occ.systemId||s.explore.configurationId!==occ.configurationId;const n={...s,view:'explore' as const,explore:{...s.explore,systemId:occ.systemId,configurationId:occ.configurationId,scenarioId:cross?c.defaultScenarioId:s.explore.scenarioId,structuralLocation:d,selection,preview:undefined,structuralHistory:[...s.explore.structuralHistory,d],traversalOrigin:undefined},returnContext:{kind:'concept_origin',conceptId:s.concepts.conceptId,label:`Return to ${s.concepts.conceptId}`} as ReturnContext};return push(n,{view:'explore',locator:d})}
export function returnToOrigin(i:DomainIndex,s:AppState){const rc=s.returnContext;if(!rc)return s;if(rc.kind==='concept_origin')return openConceptDirect({...s,returnContext:undefined},rc.conceptId);const c=cfg(i,rc.systemId,rc.configurationId);if(!c)return s;let d=exists(c,rc.structuralLocation)?rc.structuralLocation:undefined;if(!d){for(const id of [...rc.structuralPath].reverse())if(c.entities[id]){d={kind:'entity',systemId:rc.systemId,configurationId:rc.configurationId,entityId:id};break}}d??=root(rc.systemId,c);const scenario=c.scenarios[rc.scenarioId]?rc.scenarioId:c.defaultScenarioId;const selection=rc.selection&&exists(c,rc.selection)?rc.selection:undefined;return push({...s,view:'explore',explore:{...s.explore,systemId:rc.systemId,configurationId:rc.configurationId,scenarioId:scenario,structuralLocation:d,selection,preview:undefined,structuralHistory:[...s.explore.structuralHistory,d]},returnContext:undefined},{view:'explore',locator:d})}
function replay(i:DomainIndex,s:AppState,d:HistoryDestination):AppState{if(d.view==='concepts'&&d.locator.kind==='concept')return {...s,view:'concepts',concepts:{...s.concepts,conceptId:d.locator.conceptId},returnContext:undefined};if(d.view==='explore'&&('systemId'in d.locator)){const c=cfg(i,d.locator.systemId,d.locator.configurationId);if(!c)return s;const loc=exists(c,d.locator)?d.locator:root(d.locator.systemId,c);const cross=s.explore.systemId!==d.locator.systemId||s.explore.configurationId!==d.locator.configurationId;return {...s,view:'explore',explore:{...s.explore,systemId:d.locator.systemId,configurationId:d.locator.configurationId,scenarioId:cross?c.defaultScenarioId:s.explore.scenarioId,structuralLocation:loc,selection:undefined,preview:undefined}}}return s}
export function back(i:DomainIndex,s:AppState){if(s.historyIndex<=0)return s;const n=s.historyIndex-1;return {...replay(i,s,s.appHistory[n]!),historyIndex:n}}
export function forward(i:DomainIndex,s:AppState){if(s.historyIndex>=s.appHistory.length-1)return s;const n=s.historyIndex+1;return {...replay(i,s,s.appHistory[n]!),historyIndex:n}}
export const sameLocator=same;
